# Generated by Django 4.2.4 on 2023-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IhaKiralama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='agirlik',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
