# Generated by Django 4.2.4 on 2023-08-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IhaKiralama', '0002_alter_iha_agirlik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiralama',
            name='kiralama_saati',
        ),
    ]
