# Generated by Django 4.2.4 on 2023-08-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IhaKiralama', '0003_remove_kiralama_kiralama_saati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiralama',
            name='iade_tarihi',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='kiralama',
            name='kiralama_tarihi',
            field=models.DateTimeField(),
        ),
    ]
