# Generated by Django 4.2.4 on 2023-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IhaKiralama', '0004_alter_kiralama_iade_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiralama',
            name='iade_tarihi',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kiralama',
            name='kiralama_tarihi',
            field=models.DateField(),
        ),
    ]
