# Generated by Django 4.2.4 on 2023-08-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IhaKiralama', '0005_alter_kiralama_iade_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iha',
            name='eklenme_zamani',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kiralama',
            name='kiralama_zamani',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
